trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'azure-service-eshop'   
  acrName: 'eshopacr123'
  acrLoginServer: 'eshopacr123.azurecr.io'
  imageName: 'eshop-web'
  kubernetesNamespace: 'default'
  aksCluster: 'eshop-aks'
  resourceGroup: 'eshop-rg'

stages:
# -------------------------------------------------------
- stage: BuildAndPush
  displayName: 'Build and Push Image to ACR'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(acrName)

    - task: Docker@2
      displayName: 'Build and Push Image to ACR'
      inputs:
        containerRegistry: $(acrLoginServer)
        repository: $(imageName)
        command: 'buildAndPush'
        Dockerfile: 'src/Web/Dockerfile'
        tags: |
          latest
# -------------------------------------------------------
- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToK8s
    displayName: 'Deploy to Kubernetes Cluster'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    - task: Kubernetes@1
      displayName: 'Deploy to AKS'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscription: $(azureSubscription)
        azureResourceGroup: $(resourceGroup)
        kubernetesCluster: $(aksCluster)
        command: apply
        useConfigurationFile: true
        configuration: 'deploy/k8s/web-deployment.yaml'
        namespace: $(kubernetesNamespace)
