

trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'eshop-subscription'      
  acrName: 'eshopacr123'
  acrLoginServer: 'eshopacr123'
  imageName: 'eshop-web'
  kubernetesNamespace: 'default'
  aksCluster: 'eshop-aks'
  resourceGroup: 'eshop-rg'

stages:

# ---------------- Build & Push ----------------
- stage: BuildAndPush
  displayName: 'Build and Push Image to ACR'
  jobs:
    - job: Build
      pool:
        vmImage: 'ubuntu-latest'
      steps:
        - checkout: self

        # ✅ Login to ACR
        - task: Docker@2
          displayName: 'Login to ACR'
          inputs:
            command: 'login'
            containerRegistry: 'acr-eshop' 

        # ✅ Build and Push Image to ACR
        - task: Docker@2
          displayName: 'Build and Push to ACR'
          inputs:
            containerRegistry: 'acr-eshop'  
            repository: $(imageName)
            command: 'buildAndPush'
            Dockerfile: 'dockerfiles/web/Dockerfile'
            buildContext: .
            tags: |
              latest
# ------------------- Deploy to AKS -------------------
- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: BuildAndPush
  jobs:
  - job: DeployToK8s
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self

    # (Optional) Debug: list what actually exists
    - script: |
        echo "Listing manifests..."
        ls -la $(Build.SourcesDirectory)/deploy/k8s
      displayName: 'Debug: list k8s dir'

    - task: Kubernetes@1
      displayName: 'Apply Deployment'
      inputs:
        connectionType: 'Azure Resource Manager'
        azureSubscriptionEndpoint: $(azureSubscription)
        azureResourceGroup: $(resourceGroup)
        kubernetesCluster: $(aksCluster)
        namespace: $(kubernetesNamespace)
        command: apply
        useConfigurationFile: true
        configuration: |
          deploy/k8s/web-deployment.yaml
          deploy/k8s/web-service.yaml
          deploy/k8s/ingress.yaml

