apiVersion: v1
kind: Service
metadata:
  name: eshop-web-service
spec:
  type: ClusterIP
  selector:
    app: eshop-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

