apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshop-web
  template:
    metadata:
      labels:
        app: eshop-web
    spec:
      containers:
        - name: eshop-web
          image: eshopacr123.azurecr.io/eshop-web:latest
          ports:
            - containerPort: 80
          env:
            # وب را مجبور می‌کنیم روی پورت 80 گوش دهد
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:80"

            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"

            # کلیدهای اجباری که در استارتاپ خوانده می‌شوند (موقتاً دامی)
            - name: IdentityUrl
              value: "http://dummy-identity"
            - name: BasketUrl
              value: "http://dummy-basket"
            - name: CatalogUrl
              value: "http://dummy-catalog"
            - name: OrderingUrl
              value: "http://dummy-ordering"
            - name: MarketingUrl
              value: "http://dummy-marketing"
            - name: PaymentUrl
              value: "http://dummy-payment"
            - name: LocationsUrl
              value: "http://dummy-locations"
            - name: SignalrHubUrl
              value: "http://dummy-signalr"

            # اختیاری، برای اینکه بعضی فیچرهای سفارشی غیرفعال شوند
            - name: UseCustomizationData
              value: "False"

